### PR TITLE
Add necessary setup.py file to make project installable and add missing

### PR DESCRIPTION
**Pull request by SixK**
Add necessary setup.py file to make project installable and add missing `__init__.py` file for modeling directory.  
Package name will be zim_anything to avoid confusion with any existing zim python package.  
But you still import files using `import zim`. 
You should consider renaming zim directory to zim_anything and adapt documentation and demo code

Package can be installed using `pip install .` or `python setup.py install`(these way is deprecated)

### CODE REVIEW

**Comment by qjadud1994** [comment]
I appreciate your thoughtful suggestion.

I already uploaded our project to PyPI to enable `pip install zero_shot_image_matting` [(here)](https://github.com/naver-ai/ZIM?tab=readme-ov-file#installation)

We will update the project including `__init__.py` to the modeling directory, as you mentioned.

Also, we will consider changing the package name. 

Thanks.

**Comment by SixK** [comment]
OK, sorry, I did not noticed "zero_shot_image_matting" was the ZIM package. 
zim name for directory is probably OK,  
but there is a python-zim package that can be imported by pyzim.  
I feared names could conflict but it's OK.  
note that when installing, zim package seem's to create a config directory:
```
ls -ltra ~/cv/lib/python3.10/site-packages
drwxrwxr-x    3 guest guest    4096 nov.   6 10:56 config
drwxrwxr-x    5 guest guest    4096 nov.   6 10:56 zim
drwxrwxr-x 1063 guest guest   53248 nov.   6 10:56 .
drwxrwxr-x    2 guest guest    4096 nov.   6 10:56 zero_shot_image_matting-0.1.dist-info
```
it would be better to rename it zim_config like SAM2 is doing `sam2_configs` to avoid conflicts.

**Comment by qjadud1994** [comment]
We appreciate your thoughtful suggestions.

I will definitely follow your suggestions (including the config file or package name) and update the code soon.

Thanks.

**Comment by qjadud1994** [comment]
The automatic mask generation may take a long time.
Using GPU acceleration can boost the speed.

If you encounter several warning messages when running the model, your environment setting may not be suitable for GPU acceleration.

Please reconsider here: [onnxruntime installation docs](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements).

https://github.com/naver-ai/ZIM?tab=readme-ov-file#installation

**Comment by SixK** [comment]
Thank's for modifications in the project.
I Added Zim to my port of coco-annotator: https://github.com/SixK/coco-annotator-ng 
It work fine with GPU acceleration.
I still don't have Zim AutomaticMaskGenerator working, 
but it's not a useful functionality for my needs.

**Pull request closed without merging**
